const API_BASE_URL="https://milho-flakes.onrender.com";
const $=id=>document.getElementById(id);
const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const params=new URLSearchParams(location.search);const id=params.get('id');const selectedColor=params.get('color')||'';let product=null;let availableColors=[];
function fallbackProduct(){return (window.LOCAL_PRODUCTS||[]).find(x=>x.id===id);}
async function api(path){const r=await fetch(API_BASE_URL+path,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||d.error||`HTTP ${r.status}`);e.status=r.status;throw e;}return d;}
function mask(el,fn){el.addEventListener('input',()=>el.value=fn(el.value));}
mask($("cpf"),v=>v.replace(/\D/g,'').slice(0,11).replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2'));
mask($("phone"),v=>v.replace(/\D/g,'').slice(0,11).replace(/^([0-9]{2})([0-9]{5})([0-9]{0,4}).*/,'($1) $2-$3'));
mask($("cep"),v=>v.replace(/\D/g,'').slice(0,8).replace(/(\d{5})(\d)/,'$1-$2'));
$("cep").addEventListener('blur',async()=>{const cep=$("cep").value.replace(/\D/g,'');if(cep.length!==8)return;try{const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`);const d=await r.json();if(d.erro)return;$("street").value=d.logradouro||'';$("neighborhood").value=d.bairro||'';$("city").value=d.localidade||'';$("state").value=d.uf||'';$("number").focus();}catch{}});
function colorVariantFor(id,color){const safe=String(color||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return `assets/products/colors/${id}-${safe}.svg`;}
function colorPhotoFor(id,color){return (window.COLOR_PHOTOS&&window.COLOR_PHOTOS[id]&&window.COLOR_PHOTOS[id][color])||null;}
function colorDisplayFor(id,color){return colorPhotoFor(id,color)||window.FAMILY_PHOTOS?.[id]||window.REAL_PHOTOS?.[id]||colorVariantFor(id,color);}
function colorPositionFor(id,color){const o=(window.COLOR_IMAGE_ORDER&&window.COLOR_IMAGE_ORDER[id])||[];const i=o.indexOf(color);return i<0?'50%':`${Math.round((i/Math.max(1,o.length-1))*100)}%`;}
(async()=>{try{product=fallbackProduct();try{const d=await api('/api/products');product=(d.products||[]).find(x=>x.id===id)||product;}catch{}if(!product)throw new Error('Produto não encontrado.');availableColors=(window.PRODUCT_COLORS&&window.PRODUCT_COLORS[id])||product.colors||[];const color=availableColors.includes(selectedColor)?selectedColor:(availableColors[0]||'Não informado');$("summary").innerHTML=`<img class="summary-img" id="checkoutProductImage" src="${colorDisplayFor(id,color)}" alt="${product.name} ${color}" style="object-fit:cover;object-position:${colorPositionFor(id,color)} center" onerror="this.onerror=null;this.src='assets/products/${product.id}-front.svg'"><h2>${product.name}</h2><p>${product.storage}</p><div class="selected-color"><span>Cor escolhida</span><strong>${color}</strong></div><div class="delivery-box"><strong>🚚 Entrega Full</strong><br>Até 7 dias úteis</div><div class="line"><span>Produto</span><strong>${money(product.price)}</strong></div><div class="line"><span>Frete</span><strong>Grátis</strong></div><div class="total"><span>Total</span><strong>${money(product.price)}</strong></div><small>O valor é definido pelo servidor.</small>`;}catch(e){$("error").textContent=e.message;$("error").classList.remove('hidden');$("form").remove();}})();
$("form").addEventListener('submit',e=>{e.preventDefault();const cpf=$("cpf").value.replace(/\D/g,'');if(cpf.length!==11){$("error").textContent='Informe um CPF com 11 dígitos.';$("error").classList.remove('hidden');return;}const email=$("email").value.trim();if(!email||!email.includes('@')){$("error").textContent='Informe um e-mail válido.';$("error").classList.remove('hidden');return;}const color=availableColors.includes(selectedColor)?selectedColor:(availableColors[0]||'');if(!color){$("error").textContent='Selecione uma cor disponível para este aparelho.';$("error").classList.remove('hidden');return;}const order={productId:id,color,name:$("name").value.trim(),email,cpf,phone:$("phone").value.trim(),shipping:{cep:$("cep").value.trim(),street:$("street").value.trim(),number:$("number").value.trim(),complement:$("complement").value.trim(),neighborhood:$("neighborhood").value.trim(),city:$("city").value.trim(),state:$("state").value,reference:$("reference").value.trim()}};sessionStorage.setItem('iphoneExpressOrder',JSON.stringify(order));location.href=`pagamento.html?id=${encodeURIComponent(id)}&color=${encodeURIComponent(color)}`;});
