const API_BASE_URL="https://milho-flakes.onrender.com"; const $=id=>document.getElementById(id); const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const params=new URLSearchParams(location.search); const id=params.get('id'); const urlColor=params.get('color')||''; let product,tx='';
function fallbackProduct(){return (window.LOCAL_PRODUCTS||[]).find(x=>x.id===id);}
function colorVariantFor(id,color){const safe=String(color||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); return `assets/products/colors/${id}-${safe}.svg`;}
function colorDisplayFor(id,color){return (window.COLOR_PHOTOS&&window.COLOR_PHOTOS[id]&&window.COLOR_PHOTOS[id][color])||colorVariantFor(id,color);}
async function api(path,opt={}){const r=await fetch(API_BASE_URL+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d;}
function setResult(text,error=false){$("result").textContent=text;$("result").className=error?'message error':'message';}
(async()=>{try{const order=JSON.parse(sessionStorage.getItem('iphoneExpressOrder')||'null');if(!order||order.productId!==id)throw new Error('Dados do pedido não encontrados. Volte ao produto e preencha a entrega novamente.');product=fallbackProduct();try{const d=await api('/api/products');product=(d.products||[]).find(x=>x.id===id)||product;}catch{}if(!product)throw new Error('Produto não encontrado.'); const chosenColor=order.color||urlColor||''; const paymentPhoto=colorDisplayFor(id,chosenColor)||`assets/products/${product.id}-front.svg`; $("summary").innerHTML=`<img class="summary-img" src="${paymentPhoto}" alt="${product.name} ${chosenColor}" onerror="this.onerror=null;this.src='assets/products/${product.id}-front.svg'"><h2>${product.name}</h2><p>${product.storage}</p><div class="selected-color"><span>Cor escolhida</span><strong>${order.color||'Não informado'}</strong></div><div class="delivery-box"><strong>🚚 Entrega Full</strong><br>Até 7 dias úteis</div><div class="line"><span>Produto</span><strong>${money(product.price)}</strong></div><div class="line"><span>Frete</span><strong>Grátis</strong></div><div class="total"><span>Total</span><strong>${money(product.price)}</strong></div>`;$("hello").textContent=`Olá, ${order.name}. O valor final do pedido é:`;$("total").textContent=money(product.price);const data=await api('/api/deposit',{method:'POST',body:JSON.stringify({productId:order.productId,payerName:order.name,payerDocument:order.cpf,email:order.email,phone:order.phone,shipping:order.shipping,color:order.color})});tx=data.transactionId||data.id||'';sessionStorage.setItem('iphoneExpressTransaction',tx);if(data.qrcodeUrl)$("qr").src=data.qrcodeUrl; if(data.copyPaste)$("copyPaste").value=data.copyPaste;$("loading").classList.add('hidden');$("pix").classList.remove('hidden');$("statusText").textContent=`Status: ${data.status||'PENDING'}`;}catch(e){$("loading").textContent=`Não foi possível gerar o Pix: ${e.message}. Verifique se o backend do Render está online.`;$("loading").className='message error';}})();
$("copy").addEventListener('click',async()=>{try{await navigator.clipboard.writeText($("copyPaste").value);setResult('Pix Copia e Cola copiado.');}catch{setResult('Não foi possível copiar automaticamente.',true);}});
$("check").addEventListener('click',async()=>{if(!tx){setResult('Transação ainda não foi criada.',true);return;}try{const d=await api('/api/transactions/check?transactionId='+encodeURIComponent(tx));$("statusText").textContent=`Status: ${d.status||d.transactionStatus||'ATUALIZADO'}`;setResult(JSON.stringify(d));}catch(e){setResult(e.message,true);}});
